### ISSUE TITLE
Buggy `ScalarDate.newYear`

### ISSUE THREAD

**Issue by AdrienChampion** [ammkrn/timelib#2]
I'm pretty sure there's a bug [here](https://github.com/ammkrn/timelib/blob/185e8ea7c8b4274f2cb7ecba4c2e785c6e97cf15/Timelib/Date/Basic.lean#L14):

```lean
def ScalarDate.newYear (year : Year) : ScalarDate := firstOfTheMonth 1 1
```

It should probably be

```lean
def ScalarDate.newYear (year : Year) : ScalarDate := firstOfTheMonth year 1
```

**Comment by ammkrn** [comment]
That does seem like a bug. I'll spend some time with this repo in the coming week. When I left off, I was not skilled enough to overcome the lack of automation for arithmetic and deal with the frequent changes to the basic hierarchies in Mathlib. I think some of that has improved, but now I'm out of practice with the Lean front end and mathlib (c'est la vie).

fwiw there was one other big architectural change I want to make that I remember feeling was a big improvement and allowed the whole hierarchy to make sense, which is to change the time zone and leap second concepts to just be structures that described the required functions, something like:

```
abbrev NegSiPow := { z : Int // z <= 0 }

structure NaiveDateTime (p : NegSiPow) where
  val : Int

structure LeapSeconds where
  ident : String
  apply (p : NegSiPow) (tai : NaiveDateTime p) : SignedDuration p
  remove (p : NegSiPow) (zulu : NaiveDateTime p) : SignedDuration p

structure TimeZone where
  ident (p : NegSiPow) (zulu : NaiveDateTime p) : String
  offset (p : NegSiPow) (zulu : NaiveDateTime p) : SignedDuration p

structure DateTime (precision : NegSiPow) (L : LeapSeconds) (Z : Timezone) extends NaiveDateTime precision

structure HDateTime where
  precision : NegSiPow
  L : LeapSeconds
  Z : Timezone
```

If you're using what's in this repo already to do your own thing you can obviously ignore this, but just a heads up this is probably the way to do it. The current TimeZone stuff is half baked and doesn't capture seasonal time zones in the way the above implementation is able to. I think I also reached the conclusion that `ClockTime` could be removed and just replaced with a duration mod 24 hours for less code.

If you're doing something with time and you'd like to talk about anything, I'm Chris Bailey on the Lean zulip (https://leanprover.zulipchat.com/#user/228466)
